[package]
name = "rdbms"
version = "0.1.0"
authors = ["Yuta Saito <uc4w6c@bma.biglobe.ne.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
